[Rainmeter]
Update=1000
AccurateText=1
DynamicWindowSize=1

@include=#@#Variables.inc
@include2=#@#Styles.inc

;=========================
; Measures
;=========================

[MeasureHour]
Measure=Time
Format=%H

[MeasureMinute]
Measure=Time
Format=%M

[MeasureDay]
Measure=Time
Format=%a

;=========================
; Meters
;=========================

[MeterHour]
Meter=String
MeterStyle=StyleBig
MeasureName=MeasureHour
X=#ClockX#
Y=#HourY#
Text="%1"

[MeterMinute]
Meter=String
MeterStyle=StyleBig
MeasureName=MeasureMinute
X=#ClockX#
Y=#MinuteY#
Text="%1"

[MeasureDayFull]
Measure=Time
Format=%a

[MeasureDayW]
Measure=Time
Format=%a
Substitute="Mon":"M","Tue":"T","Wed":"W","Thu":"T","Fri":"F","Sat":"S","Sun":"S"

[MeasureDayE]
Measure=Time
Format=%a
Substitute="Mon":"O","Tue":"U","Wed":"E","Thu":"H","Fri":"R","Sat":"A","Sun":"U"

[MeasureDayD]
Measure=Time
Format=%a
Substitute="Mon":"N","Tue":"E","Wed":"D","Thu":"U","Fri":"I","Sat":"T","Sun":"N"

[MeterDayW]
Meter=String
MeterStyle=StyleAccent
MeasureName=MeasureDayW
X=#DayLeftX#
Y=#DayY#
Text="%1"

[MeterDayE]
Meter=String
MeterStyle=StyleAccent
MeasureName=MeasureDayE
X=#DayMidX#
Y=#DayY#
Text="%1"

[MeterDayD]
Meter=String
MeterStyle=StyleAccent
MeasureName=MeasureDayD
X=#DayRightX#
Y=#DayY#
Text="%1"