[StyleBig]
FontFace=#Font#
FontSize=#BigFont#
FontColor=#TextColor#
AntiAlias=1
StringStyle=Bold
StringAlign=Center
InlineSetting=CharacterSpacing | 8

[StyleMedium]
FontFace=#Font#
FontSize=#MediumFont#
FontColor=#TextColor#
AntiAlias=1

[StyleAccent]
FontFace=#Font#
FontSize=#SmallFont#
FontColor=#AccentColor#
AntiAlias=1
StringStyle=Bold
StringAlign=Center
StringCase=Upper
InlineSetting=CharacterSpacing | 0